//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT_LAB_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carts()
        {
            this.Cart_Goods = new HashSet<Cart_Goods>();
        }
    
        public int Cart_id { get; set; }
        public int ID_status { get; set; }
        public int ID_user { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_Goods> Cart_Goods { get; set; }
        public virtual Cart_statuses Cart_statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
