//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT_LAB_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Goods
    {
        public int Cart_Goods_id { get; set; }
        public int ID_cart { get; set; }
        public int ID_goods { get; set; }
        public int amount { get; set; }

        public decimal cum_sum { get; set; }


        public virtual Carts Carts { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
