//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT_LAB_5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OzonEntities1 : DbContext
    {
        public OzonEntities1()
            : base("name=OzonEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorizations> Authorizations { get; set; }
        public virtual DbSet<Cart_Goods> Cart_Goods { get; set; }
        public virtual DbSet<Cart_statuses> Cart_statuses { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<Goods_categories> Goods_categories { get; set; }
        public virtual DbSet<Package_types> Package_types { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Pvzs> Pvzs { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual int BackupOzon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BackupOzon");
        }
    }
}
