//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACT_LAB_5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Carts = new HashSet<Carts>();
        }
    
        public int User__id { get; set; }
        public string User__name { get; set; }
        public string User__surname { get; set; }
        public string User__middlename { get; set; }
        public int ID_pvz { get; set; }
        public int ID_Auth { get; set; }
        public int ID_Role { get; set; }
    
        public virtual Authorizations Authorizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual Pvzs Pvzs { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
